// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qGEVy48no60hWdjctQu2VWtbbgtCf84',
    appId: '1:730297663367:web:8f28ff31666b01f96e5d22',
    messagingSenderId: '730297663367',
    projectId: 'musaka-d9ae2',
    authDomain: 'musaka-d9ae2.firebaseapp.com',
    storageBucket: 'musaka-d9ae2.appspot.com',
    measurementId: 'G-Q5RRY3C36R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp6yoomT7nQ4ZxY6__tSZ8YJiSNeTyQ5U',
    appId: '1:730297663367:android:df5823653e77a54b6e5d22',
    messagingSenderId: '730297663367',
    projectId: 'musaka-d9ae2',
    storageBucket: 'musaka-d9ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrOiTAuVLIXKaYbUCja3Yt6YWHBLCDl04',
    appId: '1:730297663367:ios:7382edf8007013616e5d22',
    messagingSenderId: '730297663367',
    projectId: 'musaka-d9ae2',
    storageBucket: 'musaka-d9ae2.appspot.com',
    iosBundleId: 'com.example.ikaMusaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrOiTAuVLIXKaYbUCja3Yt6YWHBLCDl04',
    appId: '1:730297663367:ios:4dbb361e85d40dac6e5d22',
    messagingSenderId: '730297663367',
    projectId: 'musaka-d9ae2',
    storageBucket: 'musaka-d9ae2.appspot.com',
    iosBundleId: 'com.example.ikaMusaka.RunnerTests',
  );
}
